### ISSUE TITLE
Firmware Installer doesn't install properly on my Arduino.

### ISSUE THREAD

**Issue by Mavi222** [t3knomanzer/maxmix-software#103] opened 2020-07-30 23:01 UTC
The installer doesn't finish properly.

```Downloading version 0.10.6...
Installing file C:\Users\Mavi\AppData\Local\Temp\Maxmix.0.10.6.hex to COM3

avrdude.exe: Version 6.3-20171130
             Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
             Copyright (c) 2007-2014 Joerg Wunsch

             System wide configuration file is "C:\Users\Mavi\AppData\Roaming\Ruben Henares\Maxmix\FirmwareInstaller\Resources\avrdude.conf"

             Using Port                    : COM3
             Using Programmer              : arduino
             Overriding Baud Rate          : 57600
             AVR Part                      : ATmega328P
             Chip Erase delay              : 9000 us
             PAGEL                         : PD7
             BS2                           : PC2
             RESET disposition             : dedicated
             RETRY pulse                   : SCK
             serial program mode           : yes
             parallel program mode         : yes
             Timeout                       : 200
             StabDelay                     : 100
             CmdexeDelay                   : 25
             SyncLoops                     : 32
             ByteDelay                     : 0
             PollIndex                     : 3
             PollValue                     : 0x53
             Memory Detail                 :

                                      Block Poll               Page                       Polled
               Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
               flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
               lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
               hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
               efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
               lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
               calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
               signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

             Programmer Type : Arduino
             Description     : Arduino
             Hardware Version: 2
             Firmware Version: 1.16
avrdude.exe: stk500_recv(): programmer is not responding
avrdude.exe: stk500_recv(): programmer is not responding
avrdude.exe: stk500_recv(): programmer is not responding
avrdude.exe: stk500_recv(): programmer is not responding
```

**Expected behavior**
Install properly

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 x64

I tried two boards but they both don't work. 
It's these ones (with USB-C):
https://www.aliexpress.com/item/4000579100527.html
Could the USB-C be an issue? Or what should I try to do? 
I am sorry I am really noob with the Arduinos.

Have a great day and thanks for an answer,

Mavi

**Comment by t3knomanzer** [comment] 2020-07-30 23:19
Does it work if you install it from the Arduino IDE?
There could be a few things causing it not to work.
1. Have you selected the correct COM port?
2. Is the port being used by any other application (maxmix, arduino, etc)?
3. Does the MCU have a bootloader flashed?
4. Have you selected the correct bootloader option in the firmware installer?

**Comment by Mavi222** [comment] 2020-07-30 23:47
1. Yes I selected the correct COM port, I also tried multiple USBs just in case
2. The Maxmix crashes whenever I have it open and the MCU connected. AFAIK I didn't have open any app that could use that port. 
3. The seller on the aliexpress has it written in the description so I hope it does. 
4. You mean the old and new one? Didn't know which one to choose so I left it on the default value. When the firmware install failed, I also tried the other bootloader option.

I think the MCU got partially flashed or something, because I could see the maxmix logo on the display, and I could see some programs in the audio settings of the programs I had open. But when I went and tried to control the volume with it, it did nothing, and shortly after I noticed that the maxmix icon in the tray vanished, so it keeps crashing.

I think the first install, the installation failed on checking if it is installed properly or something (sorry I am not at the computer anymore, I will send you that log tomorrow if needed.

**Comment by t3knomanzer** [comment] 2020-07-31 18:55
That feels then like the problem may be on the PC side and not the device.
I would try to deploy the firmware using the arduino IDE to reduce the scope of the issue.
It could be so many different things that you're going to need to follow a process of elimination.

**Comment by Mavi222** [comment] 2020-07-31 18:59
Okay I figured it out, the USB-C version of the Arduino Nano has different chip than the one that is necessary in your part list... It has ft232rl instead of CH340. I just tried the Mini-USB version (with CH340) and that one works fine. Bummer. I really wanted to have it on USB-C so it's more "modern" and more cables at my home are USB-C.

I guess there is no way to make the ft232rl chip work with the Maxmix?

**Comment by t3knomanzer** [comment] 2020-07-31 19:48
I am not in front of the computer now but it could be caused by the DTR and RTS port configuration, not sure what the requirements for the FT232 are. 

If you can, try setting the DtrEnable and RtsEnable of the SerialPort instance to true in both, the  DiscoveryService (line 91) and the CommunicationService (line 130).

**Comment by t3knomanzer** [comment] 2020-07-31 21:26
If you don’t know how to do it, I can compile a version for you to try. 

Take into account that there is a ton of different hardware out there and I can’t implement support for it all. 
The code is built to support a specific set of parts which are the ones provided in the build instructions. 
Otherwise it would mean I’d have to have all possible hardware myself and test every release with a wide range of configurations. 

As a general rule of thumb, if you’re using hardware different than the official one, make sure you are comfortable debugging/troubleshooting code.  Then if you can contribute those changes back to the repo, the whole community benefits from it. 

I’m happy to help and add support for other hardware as long as the amount of work is reasonable. That was the case for instance when I added support for old/new bootloader, it was a straightforward change and a ton of people benefited from it. 

If adding support for the FT232 is simple and the means you now can use USB-C and Micro USB versions of the Nano, I’m more than happy to implement it. 

Let me know if you’re able to make the changes and test it or you’d like me to compile a version for you. 

Thanks for taking the time to report this, it’s super appreciated.

**Comment by Mavi222** [comment] 2020-07-31 21:36
If it isn't much hassle, I would really appreciate if you tried to compile it yourself. I will try to help you as much as possible. I am not a programmer and I have no idea what to do.

Really appreciate your help!

**Comment by t3knomanzer** [comment] 2020-07-31 23:28
Try this. Just unzip it and run the Maxmix.exe executable inside. Be careful if you have an anti-virus it may delete the file.

[Debug.zip](https://github.com/t3knomanzer/maxmix-software/files/5009371/Debug.zip)

**Comment by pbanj** [comment] 2020-08-01 06:15
I wish I had seen this before ordering the usbc one. When it gets here if you still need testers I'm more than happy to help.

**Comment by Mavi222** [comment] 2020-08-01 06:52
> [Debug.zip](https://github.com/t3knomanzer/maxmix-software/files/5009371/Debug.zip)

I tried running the Maxmix.exe and now it just shows the Maxmix logo on the display and it blinks every 5 seconds, turning or pressing the encoder does nothing. And the Maxmix doesn't recognize the device.

**Comment by t3knomanzer** [comment] 2020-08-01 07:41
Yeah makes sense. It’s resetting it continuously which is the same behavior you get with the CH340. That means that wasn’t not the problem. 

Did you try installing the firmware using the arduino IDE?

Ruben Henares

**Comment by Mavi222** [comment] 2020-08-01 18:01
> Did you try installing the firmware using the arduino IDE?

Now that I've tried uploading a simple blink sketch, I have problem doing even that. Hmmm that's weird. I've contacted the seller on Aliexpress, maybe he will lead me to the correct uploading method. Or both of my USB-C Arduinos are broken, that might be the case too. 

old bootloader:
![old bootloader](https://user-images.githubusercontent.com/20151483/89107363-e690f600-d430-11ea-97c2-ccf164c181ec.png)

new bootloader:
![new bootloader](https://user-images.githubusercontent.com/20151483/89107364-e98be680-d430-11ea-9fb1-9f6fea03c633.png)

in the meantime I ordered the [FT232RL FTDI USB To TTL Serial Converter Adapter Module](https://www.banggood.com/FT232RL-FTDI-USB-To-TTL-Serial-Converter-Adapter-Module-p-917226.html). No idea what that does, but people are uploading sketches to the Arduino Mini Pro with this thing, so it might work for the Nano with this weird chip? (I have no idea what I am doing)

**Comment by t3knomanzer** [comment] 2020-08-01 18:11
Ok so the problem has nothing to do with Maxmix then. 
What the adapter does is the same as the FT232 chip on your nano. So by using the adapter to upload the code directly to the AtMega328P you bypass the onboard chip. The adapter is used for boards that don’t have a USB to Serial converter on board. 

Ruben Henares

**Comment by t3knomanzer** [comment] 2020-08-01 18:12
I’m going to close this bug since it’s not related to Maxmix. 

Thank you!

**Comment by Mavi222** [comment] 2020-08-01 18:50
Alright, I am sorry that I bothered you with it. I didn't know it's not related. 

I also just noticed that maybe the nano has just the ch340 chip, because the description on the seller's page is written weird. 

Have a great day!

**Comment by t3knomanzer** [comment] 2020-08-01 19:32
Oh no worries at all! I’m happy to help!
Btw, did you install the FTDI drivers?

https://learn.sparkfun.com/tutorials/how-to-install-ftdi-drivers/all

Ruben Henares

**Comment by pbanj** [comment] 2020-08-01 22:35
@t3knomanzer would you having the actual hardware be helpful at all?

**Comment by t3knomanzer** [comment] 2020-08-01 22:57
Absolutely. I’m just in the middle of moving to a new place so I don’t want to order anything to my current address and I don’t know where I’m moving to yet 😄. 
I’ll order it as soon as I know. 

The MCU is the same one, the 328P so the code definitely works. The only thing different is the USB to Serial chip which uses the FT232 instead of the CH340.   

If you can’t  upload any sketch from the Arduino IDE it means that the computer is obviously not communicating with it correctly. That could be due to 3 reasons AFAIK.   

1. The board is fried
2. You don’t have the drivers installed
3. You are not selecting the correct board/port in the IDE. 

So first step is to check if the board is detected in the device manager.   
If it’s not recognized, install the drivers.   
If it’s still not recognized, it’s likely fried. 

If it is recognized and you can’t upload anything to it, the it’s your IDE configuration likely.

**Comment by pbanj** [comment] 2020-08-01 23:19
well once you're moved let me know and ill order you one. mine shipped yesterday so now i play the waiting game lol

**Comment by Mavi222** [comment] 2020-08-01 23:23
> Btw, did you install the FTDI drivers? https://learn.sparkfun.com/tutorials/how-to-install-ftdi-drivers/all

Yeah I tried that, I also tried flashing bootloader (in case it was badly flashed at factory or something) 

I am selecting the correct COM port, but I am not sure if I selected the correct board, I am selecting just the normal Arduino Nano board in the IDE and tried both old and new bootloader options and still get the same problems. 

I've contacted the seller, let's see what he will say about it.

**Comment by t3knomanzer** [comment] 2020-08-01 23:23
Oh that’s very nice of you! Thanks, I will!
I have an FTDI serial to usb converter so I can run some tests in the meantime. They’re not usb-c though so it’s not really a representative test.  


Ruben Henares

**Comment by t3knomanzer** [comment] 2020-08-04 20:11
Someone in Reddit got it working with the usb-c version and apparently they didn’t have any issues. 


https://www.reddit.com/r/maxmixproject/comments/i3k181/everything_finally_arrived_now_with_usbc/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by Mavi222** [comment] 2020-08-04 20:57
Hmmm I guess that confirms that my Arduinos are bad. Weird that it's all of them (I got four). Again, sorry for bothering.

**Comment by t3knomanzer** [comment] 2020-08-04 21:04
No problem at all. You may want to ask him/her for details. I’d be also surprised if all 4 were bad.

**Closed as completed by t3knomanzer** 2020-08-04 21:04 UTC
Labels: bug

**Comment by Mavi222** [comment] 2020-08-06 09:37
Alright, I know what my problem was. It was the cable. I used microUSB to USB-C kind of cable 
![APWCB081m](https://user-images.githubusercontent.com/20151483/89516562-e0a46780-d7d8-11ea-9210-a59905e20041.jpg) and it probably fried something on the boards. I tried another cable with brand new USB-C Arduino and it worked without any issues! Going to upload my remix to the thingiverse soon! (sorry for reopening this thread, you can lock it now forever)

**Comment by t3knomanzer** [comment] 2020-08-06 14:29
Yeyyy! So glad you found the issue! Thank you for being persistent! Time to enjoy. 

Ruben Henares

**Comment by pbanj** [comment] 2020-08-07 00:32
This is good to know. I'd throw that cable away as it's probably missing the pull-up resistor. It can fry any usbc device

**Comment by pbanj** [comment] 2020-08-25 00:35
https://i.imgur.com/InBOygg.gifv got my usbc arduinos and screen in today. both flashed fine. god im so excited lol

**Comment by t3knomanzer** [comment] 2020-08-25 00:52
Yeyyyyy! So exciting! Thank you so much for building it, it makes me so happy 🥳 I hope you enjoy it. 

Ruben Henares

**Comment by pbanj** [comment] 2020-08-25 00:55
no, thank you for making this. I've been stuck using an old ps3 headset because it allows me to change chat and game audio independently. because of you I'll no longer be stuck like that.

**Comment by t3knomanzer** [comment] 2020-08-25 00:57
Jajajaja. So happy to hear that! Please make sure to provide feedback and report bugs once you start using it so we can make it better. 
Would you mind sharing on twitter and Reddit? Helps a lot to grow the community!

🙏 

Ruben Henares

**Comment by pbanj** [comment] 2020-08-25 01:10
Oh I've been talking about it non stop lol. I run the Nintendo homebrew discord server which is pretty large 120k+ people. Once it's done I'll post it to reddit along with how I made my power bus.

**Comment by t3knomanzer** [comment] 2020-08-25 01:12
Oh nice! Thank you so much I appreciate it!

Ruben Henares
