### ISSUE TITLE
Add option to select the sense of rotation

### ISSUE THREAD

**Issue by maelremrem** [t3knomanzer/maxmix-software#196] opened 2020-09-15 10:28 UTC
**Guidelines**
- [x] I have reviewed the [guidelines for contributing](https://github.com/t3knomanzer/maxmix-software/blob/master/.github/CONTRIBUTING.md) to this repository.

**Is your feature request related to a problem? Please describe.**
Sometime, the encoders that came form the same vendors are working in the opposite direction.

**Describe the solution you'd like**
A nice option would be to have a setting on the pc app to select/invert the direction of the encoder

**Comment by SchemingWeasels** [comment] 2020-09-15 16:47
Duplicate of #192.

**Closed as completed by SchemingWeasels** 2020-09-15 16:47 UTC
Labels: feature, application, firmware
